[features]
seeds = false
skip-lint = false

[programs.devnet]
# solana_nft_anchor = "5NTLdHY5FkanW5D3kSi5s8KVJubksVdQA6TpNddys6wt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id-new.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
